### ISSUE TITLE
Doesn't play well with godotenv

### ISSUE THREAD

**Issue by parkr** [zenazn/goji#103]
Hey, I was just working on a goji project (porting it from Martini, which is a lot slower) and was noticing that my `.env` isn't working. When I set `PORT=7413`, Goji starts up with port of `8000`, the default. I think this is a "race condition," in that [`bind.WithFlag()`](https://github.com/zenazn/goji/blob/709dbfa7bd7cfa5a2174cc96da25c1a2030b972f/serve.go#L15) is called too early.

So the only way to change the default bind address is to set the environment variable *before* invoking the program either as `export PORT=7413 && ./server` or `PORT=7413 ./server`. I can't place the env vars in my `.env` and just run `./server` for this one variable, only.

Example program:

```go
package main

import (
	"log"
	"net/http"

	_ "github.com/joho/godotenv/autoload"
	"github.com/zenazn/goji"
)

func SayHello(w http.ResponseWriter, req *http.Request) {
	fmt.Fprintf(w, "Hello, world\n")
}

func main() {
	goji.Get("/", SayHello)
	goji.Serve()
}
```

Place `PORT=7413` in your `.env` file, then run `go build && ./test` and see that it runs as port `8000`.

**Comment by elithrar** [comment]
You're sourcing your env file into the current shell, right? It should
actually be "export PORT=7413" there too else the shell won't see it.

**Comment by parkr** [comment]
@elithrar No, the point is that I'd like to be able to use `github.com/joho/godotenv/autoload` and have `bind.WithFlag()` executed at `goji.Serve()` time or something.

**Comment by zenazn** [comment]
Unfortunately I think I'm going to have to chalk this one up to a design failing of godotenv: it's unreasonable to ask Go packages to avoid the use of `init()` functions when performing initialization (including initialization that involves environment variables), and Go's program start-up model doesn't leave enough wiggle room to let godotenv do the thing it's trying to do.

I know this is an entirely unhelpful answer, so let me propose a few hacks:

1. Ditch package `goji` entirely. There's intentionally not much code at the top-level (it's pretty much entirely glue code), and I expect most large/complex applications will "graduate" to rolling their own muxes anyways for increased flexibility. An easy way to start here is by copy-and-pasting the package into your project verbatim, and changing a few import lines to point to the right place.
2. Reach in and sketch on the `-bind` flag (using the functions in package flag). Really the only thing you need is to reset the default value of `-bind` to `bind.Sniff()`, and Go gives you enough rope to do this yourself (take a look at `FlagSet.Lookup()`, for instance).

**Comment by zenazn** [comment]
And to specifically address your suggestion to put `bind.WithFlag()` in `goji.Serve()`: that won't work because many (most?) users call `flag.Parse()` themselves, e.g. so they have control over displaying any errors that flag parsing results in, or so they can perform initialization of their own with the results of flag parsing.

**Comment by parkr** [comment]
Ok, I'll give this a try. Thanks!
