### ISSUE TITLE
Feature request: create handler groups to reduce path replication

### ISSUE THREAD

**Issue by parkr** [zenazn/goji#104]
If you have three routes, all of which start with `/api/1`, you're left maintaining them separately:

```go
goji.Get("/api/1/messages", getMessages)
goji.Post("/api/1/messages", postMessages)
goji.Get("/api/1/messages/:id", getMessageById)
```

It'd be nice to be able to group them:

```go
goji.Group("/api/1", func(r goji.Router) {
    goji.Get("/messages", getMessages)
    goji.Post("/messages", postMessages)
    goji.Get("/messages/:id", getMessageById)
})
```

Thoughts?

**Comment by zenazn** [comment]
Fun fact: you can already do this!

https://github.com/zenazn/goji/blob/master/example/main.go#L43-L60

(documenting this better is definitely on my TODO list: you're far from the first person to be confused about sub-routes)

**Comment by parkr** [comment]
Was just looking for a place to document this and couldn't find a suitable place. Thoughts?
