### ISSUE TITLE
Build and Deploy to production

### ISSUE THREAD

**Issue by mewben** [zenazn/goji#105]
Hi, I'm new to Go and goji. Are there any steps to build and deploy a goji app into production? Please help.

**Comment by badoet** [comment]
you can run go build main.go 
and use the shell script below to run the app.
you will need nohup installed.
you can put in the environment variable at the top, in this example i set PRODUCTION=1
you can change the pid location (/home/pids/app.pid) and the log location (/tmp/app.out) where you see fit

```
#!/bin/bash

export PRODUCTION=1

start() {
    cd /home/deploy/app;
    exec nohup /home/deploy/app/main > /tmp/app.out 2>&1&
    echo $! > /home/pids/app.pid
    disown
}

stop() {
    kill `cat /home/pids/app.pid`
}


case $1 in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
  echo "usage: knife-knife-server-daemon {start|stop}" ;;
esac
exit 0
```

**Comment by mewben** [comment]
Thank you very much @badoet... I'll try those.
