### ISSUE TITLE
Error with go1.4

### ISSUE THREAD

**Issue by mewben** [zenazn/goji#106]
```
../../github.com/zenazn/goji/default.go:4: import /Users/user/go/pkg/darwin_amd64/github.com/zenazn/goji/web.a: object is [darwin amd64 go1.3.3 X:precisestack] expected [darwin amd64 go1.4 X:precisestack]
```

**Comment by mkrull** [comment]
You need to recompile your packages with your current go version. This error is not goji specific and will occur with other packages as well.

**Comment by mewben** [comment]
I deleted the zenazn folder and ran `go get github.com/zenazn/goji` again.. Thanks...
