### ISSUE TITLE
Error running the Gritter example with go1.4

### ISSUE THREAD

**Issue by mewben** [zenazn/goji#107]
I ran `go build *.go` and throws this error:

```
# command-line-arguments
./main.go:18: import /Users/user/go/pkg/darwin_amd64/github.com/goji/param.a: object is [darwin amd64 go1.3.3 X:precisestack] expected [darwin amd64 go1.4 X:precisestack]
```

**Comment by mkrull** [comment]
Still the same. As issue #106. Try to remove the pkg folder of goji instead of the src because precompiled object files are stored in pkg.

**Comment by mewben** [comment]
Thanks @mkrull ... Sorry for my noobiness... Another thing... Do you have any idea how to get rid of the firewall popups everytime I run the app? I'm using mac... (Sorry again for out of topic)

**Comment by mkrull** [comment]
On Windows the popup goes away if you bind to localhost instead of *. That should work on Mac OS as well. Try starting your application with `-bind localhost:8000` parameter.

**Comment by mewben** [comment]
Perfect! Thanks again..
