### ISSUE TITLE
isTTY heuristic does not work in bash on windows

### ISSUE THREAD

**Issue by mrgamer** [zenazn/goji#108]
It might be a not-so popular to use a Bash console on Windows, but it's really the only way when developing.

Go coloring packages works wonders, but [this code](https://github.com/zenazn/goji/blob/master/web/middleware/terminal.go#L34-L49) doesn't really discern that this shell handles well ANSI coloring

If I figure out how to detect it, i'll pop a PR... might be interesting to know if you would fancy supporting this platform

**EDIT**: more info

Actually `Stat` fails on `os.Stdout`. Quite right...
```
os.Stdout.Stat error: GetFileInformationByHandle /dev/stdout: The handle is invalid.
```

**Comment by zenazn** [comment]
Oh that's exciting.

The short answer here is that I'd love for Windows to be a supported platform—and thanks to the generosity of a few early contributors, I think Goji does, in fact, work on Windows—but I don't have easy access to a Windows machine (nor, to be completely frank, is this something I have given much thought to fixing) so unfortunately I'm not really in a great position to maintain Windows compatibility over time.

Let me know if you do figure it out though—I'd be delighted to take a patch!

**Comment by mkrull** [comment]
@mrgamer I guess this a more general go-on-windows issue.

    package main

    import (
            "fmt"
            "os"
    )
    
    func main() {
            stat, err := os.Stdout.Stat()
            if err != nil {
                    fmt.Println(err)
            }
            fmt.Printf("%+v\n", stat)
    } 

This will not work at all in cmd.exe or native bash.exe. In cygwin bash it works fine because cygwin provides `/dev/std*`

**Comment by zenazn** [comment]
Since this issue has been idle for a few months I'm going to close it out. I'd still be excited to get `isTTY` working on Windows, but without some help from the community I'm afraid there's very little I can do :/

**Comment by moorereason** [comment]
In case someone wants to enhance this package later:
 - TTY detection: https://github.com/mattn/go-isatty
 - Terminal colors for Windows:  https://github.com/mattn/go-colorable

**Comment by mrgamer** [comment]
wow, nice input @moorereason
