### ISSUE TITLE
Set to production setting

### ISSUE THREAD

**Issue by badoet** [zenazn/goji#110]
is there a goji.SetMode(goji.ReleaseMode) setting?
to set it to a production release
or maybe a way to turn off the access log?
the log getting very big and hard to maintain.

**Comment by zenazn** [comment]
Goji doesn't have a concept of modes—in some sense it's always in "production" mode.

If you're looking to log less (or perhaps not log at all) you can always remove the request logger middleware, or perhaps set the output of the default logger (http://golang.org/pkg/log/#SetOutput) to `ioutil.Discard`.

If you'd like to keep logs around, however, I'd suggest looking into `logrotate`, which will help you compress and delete old logs on a schedule.

**Comment by zenazn** [comment]
Just to bump this thread—were you able to solve your problem? If so, feel free to close this issue, but if not I'm more than happy to try to help out!

**Comment by badoet** [comment]
the logrotate somehow not working well for me. it somehow remove my original log file. 
would be good to have an option to turn the access log to mute for goji. 
coz this will still incurr cpu io which will cause jittery for performance sensitive app

**Comment by elithrar** [comment]
You can just use `goji.Abandon(middleware.Logger)` or create a "clean" mux
without any middleware applied - e.g.

r := web.New()
r.Get("/", IndexHandler)

graceful.ListenAndServe(":8000", r)

The console logger is ultimately just there for convenience during
development. There's no built-in logrotate function—if you need that, I'd
look at using lumberjack (https://github.com/natefinch/lumberjack) or
capturing your Go application's stdout with a daemon manager (such as
Supervisor or Upstart).

**Comment by badoet** [comment]
Awesome! thats helps alot for me. thx
