### ISSUE TITLE
Remove global middleware from subrouter

### ISSUE THREAD

**Issue by TheAJ** [zenazn/goji#114]
Hi,

Is there a way to remove a global middleware stack from a subrouter? I do not want to run one of them for a certain section.

For example, I want to run the middle on every path, except ones matching `/assets/*`

**Comment by 0xdabbad00** [comment]
See https://github.com/zenazn/goji/issues/64

**Comment by TheAJ** [comment]
I did look at the example, and I tried something like this:

```go
goji.Use(authMiddleware)

assets := web.New()
goji.Handle("assets/*", assets)

admin.Use(middleware.SubRouter)
admin.Abandon(authMiddleware)
goji.Get("/*", http.FileServer(http.Dir("./public/")))

```

It doesn't seem to be taking any affect.

**Comment by elithrar** [comment]
Middleware is "already" applied prior to the sub-router being passed the
request, so by then it's too late. One approach would be to:

r := web.New()

things := web.New()
r.Handle("/things/*", things)
// Only applied to the `things` sub-router
things.Use(your.Middleware)
things.Use(your.OtherMiddleware)


admin := web.New()
r.Handle("/admin/*", admin)
// Only applied to the `admin` sub-router
// Does mean there's some repetition if you want multiple top-level routes
admin.Use(your.Middleware)
admin.Post("/admin/login/auth", AuthHandler)

static := web.New()
r.Handle("/assets/*", static)
// Only applied to the `static` sub-router
static.Use(some.Middleware)

graceful.ListenAndServe("127.0.0.1:8000", r)


That's how I currently handle it in my application. If you have a bunch of
top-level sub-routers (i.e. "/posts/*", "/admin/*", "/stuff/*") that need
to use the same middleware then it it does introduce some repetition in
having to re-apply the middleware to each sub-router.

**Comment by zenazn** [comment]
Yeah, sorry about this—it's a known pain-point that there's not an easy way to fix. A couple of proposals have been bouncing around (including "inline" middleware on individual routes, which works better if there are many sorts of endpoints each with their own middleware stacks), but nothing has really stuck yet.

One crazy idea: make a custom `Pattern` that accepts all routes that do *not* match some prefix, and apply middleware on a sub-router attached to that `Pattern`. I'd love to know if that's actually a workable design in practice, so let me know if you end up experimenting with it.

**Comment by zenazn** [comment]
Just wanted to check up on this issue—is there anything else I can help with?

I just committed a change that might be of use—https://github.com/zenazn/goji/commit/707cf7e127e738386a38fa9fda3834315892b434. If you perform routing before authentication you should be able to peek at the matched `Pattern` and figure it out from there.
