### ISSUE TITLE
implement live reload by default

### ISSUE THREAD

**Issue by mykhael** [zenazn/goji#115]
I believe that implementing live reload should make it much easier to check changes fairly quickly, I know that I could import the gin package from https://github.com/codegangsta/gin but adding this feature by default causes less stress and work towards new gophers

**Comment by elithrar** [comment]
As a user of Goji: I think live reload (by default!) is a trap for new
users, many of whom can forget to turn it off and suffer a big performance
penalty.

codegangsta/gin or pilu/fresh (and all the other FS watchers) do these
things pretty easily and keep "dev only logic" out of your application.

YMMV though!

**Comment by mykhael** [comment]
@elithrar I didn't think of it like that, thanks for better explaining
