### ISSUE TITLE
Handling path like routing parameter

### ISSUE THREAD

**Issue by activars** [zenazn/goji#118]
I have to implement a routing scheme look like `/api/:path`

`:path` value format is `/a/b/c`

The example url would end up with `/api//a/b/c`

Goji seems to force 301redirect URLs from `/api//a/b/c` to `/api/a/b/c`, then redirected request loses request body.

**Comment by zenazn** [comment]
You should be able to use `/api/*`, which binds `*` to `/a/b/c` when passed a url of `/api/a/b/c`

I think the double-slash thing is something net/http or net/url does, so isn't something Goji can help you solve.

**Comment by activars** [comment]
you are correct. I looked into this problem and it seems to be `net/http/server.go` behaviour.
Thanks for the quick response.
