### ISSUE TITLE
Use gpokg.in for API versioning?

### ISSUE THREAD

**Issue by amoghe** [zenazn/goji#119]
Recently (hours ago) aee21eb0bd4d983cc26959f10ab28d540f91f884 "broke" my application because `web.HanderFunc` no longer exists in goji. To allow pkg contributors/maintainers to continue developing new features without breaking existing users, it may be useful to version the API using `gopkg.in`. This way new features can be added (that introduce API breakage) without disrupting existing users, instead giving them sufficient time to move over to the new version of the API.

I understand that another option is for consumers of goji to use `godep` and pin themselves to a particular version of the code, but I believe API versioning is also an elegant concept.

Thoughts?

**Comment by zenazn** [comment]
First of all—sorry about that! It's hard to get a feel for how often a feature like that is actually being used in the wild, and it looks like I made a bad call. (Separately, I'd be curious to hear what you were using `web.HandlerFunc` for—if there's a use case I didn't think about, I'm happy to revert that change)

As for the larger question, I'm actually gearing up for a 1.0 release, and am trying to get all of the breaking changes I've been thinking about doing for the past year out of my system. I hope to cut that release in the coming month or so. At that point, I intend on following the Go stdlib's strict compatibility standards, at which point the whole question of using a tool like gopkg.in becomes moot.

**Comment by cbroglie** [comment]
I am using `web.HanderFunc` to create per-endpoint "middleware" which requires access to `c.URLParams`, such as authenticating a RESTful endpoint.

Consider some endpoints:
```go
func setup() {
	// ...
	// Allow any authenticated user to read data
	Get("/user/:user", auth.EnforceC(getUser, auth.AnyUserAuth)).
	// But limit users to only modifying their own data
	Post("/user/:user", auth.EnforceC(postUser, auth.SelfUserAuth)).
	// ...
}

func getUser(c web.C, w http.ResponseWriter, r *http.Request) {
	// ...
}

func postUser(c web.C, w http.ResponseWriter, r *http.Request) {
	// ...
}
```

And then the `auth` package:
```go
func Enforce(h http.HandlerFunc, access AccessLevel) web.Handler {
	fn := func(c web.C, w http.ResponseWriter, r *http.Request) {
		if checkAuth(c, r, w, access) {
			h(w, r)
		}
	}
	return web.HandlerFunc(fn)
}

func EnforceC(h web.HandlerFunc, access AccessLevel) web.Handler {
	fn := func(c web.C, w http.ResponseWriter, r *http.Request) {
		if checkAuth(c, r, w, access) {
			h(c, w, r)
		}
	}
	return web.HandlerFunc(fn)
}
```

Shouldn't be too hard to work around the removal of `web.HandlerFunc`, just sharing my use case.

**Comment by zenazn** [comment]
@cbroglie—couldn't you just have returned `fn` in those cases?

**Comment by cbroglie** [comment]
Looking back, I think I just liked the simplicity of returning `web.Handler` rather than `func(c web.C, w http.ResponseWriter, r *http.Request)` or `interface{}`.

**Comment by zenazn** [comment]
Alright, it looks like I made a bad call with removing this. Reverted, and sorry for the hassle!
