### ISSUE TITLE
x509: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by funnythingz** [zenazn/goji#126]
Hi

Goji is cool software.
I have a question.

`x509: failed to load system roots and no roots provided`
This error is when image put to S3 run on docker

I heal Maybe this
https://medium.com/@kelseyhightower/optimizing-docker-images-for-static-binaries-b5696e26eb07

```go
pool = x509.NewCertPool()
pool.AppendCertsFromPEM(pemCerts)
client = &http.Client{
    Transport: &http.Transport{
        TLSClientConfig: &tls.Config{RootCAs: pool},
    },
}
```

use doing what this in goji?

Thanks!

**Comment by elithrar** [comment]
Can you post the contents of the Dockerfile your image is using?

As Kelsey points out in that article - if you're using a really minimal
image, you don't get cgo support (
http://dominik.honnef.co/posts/2013/12/cross_compiling_go_and_hidden_uses_of_cgo/)
nor the root CA certificates.

You need to copy the root CA's from somewhere else (i.e. a larger image -
i.e. Debian full), store them in your smaller image and then call
x509.NewCertPool(). You'll see that the `pemCerts` variable is a global
that just statically dumps the root CA certificates into the source (
https://github.com/kelseyhightower/contributors/blob/master/certs.go) - but
you could also put them into a file and read that in init() too.

A simpler solution is to use a full image like the 85MB Debian image and
"wear" the extra ~80MB of disk space in exchange for simpler deployment:
https://registry.hub.docker.com/_/debian/

Hope that helps. If it's not clear, post your Dockerfile :)

**Comment by elithrar** [comment]
PS: This isn't really a Goji-related issue but happy to help you get up and
running with Goji nonetheless.

**Comment by funnythingz** [comment]
@elithrar Thank you message!

I make not Dockerfile.
docker image is scratch image.

```sh
// local client
$ GOOS=linux go build -o ./app
$ tar cvfz app.tar.gz ./app
```

```sh
// vagrant CoreOS on EC2
$ cat app.tar.gz | docker import - app
$ docker run -d -p 80:8000 app /app
```

> A simpler solution is to use a full image like the 85MB Debian image and
"wear" the extra ~80MB of disk space in exchange for simpler deployment:

I think this it is proposed a Better.

Thanks!!

**Comment by funnythingz** [comment]
@elithrar 
As a result of various trial from there , it was resolved

```sh
$ docker run -v '/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt' -d -p 80:8000 app /app
```

To you I will very grateful.
Thanks!

**Comment by orian** [comment]
`apt-get install -y ca-certificates` also helps

**Comment by rijnhard** [comment]
i had a similar issue, just reinstalling `ca-certificates` failed since the java keystore crashed half way through. 

heres what i did
https://github.com/docker/docker/issues/5157#issuecomment-222100182

**Comment by astromahi** [comment]
Installing CA certificates resolved the issue (for alpine: `apk add ca-certificates`) .
