### ISSUE TITLE
parseHandler() and panic() question

### ISSUE THREAD

**Issue by sevein** [zenazn/goji#127]
Hey @zenazn,

I was reading goji's code. In particular, I have a question about `parseHandler()` in handler.go:

```go
func parseHandler(h HandlerType) Handler {
	switch f := h.(type) {
	case func(c C, w http.ResponseWriter, r *http.Request):
		return handlerFuncWrap{f}
	case func(w http.ResponseWriter, r *http.Request):
		return netHTTPHandlerFuncWrap{f}
	case Handler:
		return f
	case http.Handler:
		return netHTTPHandlerWrap{f}
	default:
		log.Fatalf(unknownHandler, h)
		panic("log.Fatalf does not return")
	}
}
```

In the default case, can't you achieve the same result just calling `log.Panicf()`? I'm not sure if I am missing something.

Thank you in advance,

**Comment by zenazn** [comment]
`log.Fatalf` calls `os.Exit` under the hood, and `os.Exit` terminates the program without `panic`'ing. Unfortunately, Go doesn't know that `log.Fatalf` doesn't return, so the extra `panic` is to appease the compiler.

**Comment by sevein** [comment]
Ouch! I see, thanks for the explanation. This is definitely not an issue in Goji :)
