### ISSUE TITLE
Feature request: include Request and ResponseWriter into C

### ISSUE THREAD

**Issue by tve** [zenazn/goji#128]
I've used goji in the past and have played with labstack/echo a bit recently. Something I really like about echo is that the Context passed to handlers includes the Request & ResponseWriter so a handler signature can be just `func handler(c *Context)`. While that seems like a trivial change what it enables is very nice. The Context provides convenience methods such as `func (c *Context) JSON(code int, v interface{})` which responds to a request with the json serialization of the object while setting the appropriate headers. In many error cases all that's needed to respond is a 1-liner like `c.String(413, "Invalid foobar parameter")`. All this is possible because these methods have the ResponseWriter available and can directly write to it.
I've been wondering whether it would make sense to add a "FullContext" type to goji and support handlers that implement a `func handler(c *FullContext)` signature to enable the above niceties. I'm happy to produce a pull request but was wondering whether this is at all interesting and what I'd have to consider.

**Comment by zenazn** [comment]
I think that heavy context objects are an anti-pattern: they effectively limit you to the ecosystem provided by your framework of choice. If you (for whatever reason) wanted to emit YAML, for instance, you'd be forced to submit a pull request upstream to add `func (*Context) YAML(code int, v interface{})` and I'd be forced to review and include it (and Goji would grow an unseemly YAML dependency). In contrast, anyone can write a helper function that takes the standard `http.ResponseWriter` interface and emit YAML, and furthermore once it has been written once it can be used with essentially any framework under the sun, including vanilla `net/http`. Several Goji-based projects at work have helper function libraries that do exactly that, and they seem to work well.

I don't want to stop you from experimenting with all-in-one objects (it should be easy to shim on top of Goji if you're interested in doing so, and I'd be happy to help you out), and it's possible that they work well for your use case, but I'm not interested in including any such functionality upstream.

**Comment by renstrom** [comment]
This is basically the reason I prefer Goji over Echo and Gin for example, that it still has the `ResponseWriter, *Request` signature part instead of including it all in the context object.

**Comment by tve** [comment]
I tried this out and wrote helpers such as:
```
func ErrorString(c web.C, rw http.ResponseWriter, code int, str string) {
	c.Env["err"] = str
	if code >= 500 {
		errStr := fmt.Sprintf("Internal Error (request ID: %s)", middleware.GetReqID(c))
		http.Error(rw, errStr, code)
	} else {
		http.Error(rw, str, code)
	}
}
```
This has worked out nicely and is actually a wash compared to labstack/echo because I could also easily define an Errorf helper and more.
In summary: thanks for a thoughtful initial response (and for developing goji)!

**Comment by zenazn** [comment]
Awesome--glad I could help!
