### ISSUE TITLE
Can't manually close hijacked connections?

### ISSUE THREAD

**Issue by yangou** [zenazn/goji#130]
I'm new to Golang in general.

The issue I'm facing right now is that I use Gorilla's websocket package to upgrade the `http.ResponseWriter` and the `http.Request` to the `websocket.Conn`.

However after some debugging, I found the underlying `websocket.Conn` actually has a disowned=true field set. So that I can't manually call `Close()` on that connection. Doing so, will give me this `errClosing = errors.New("use of closed network connection")`

In `github.com/zenazn/goji/graceful/listener/conn.go`
```
func (c *conn) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if c.closed || c.disowned {
		return errClosing
	}

	c.closed = true
	c.shard.disown(c)
	defer c.shard.wg.Done()

	return c.Conn.Close()
}
```

Is there a way that I can manually manage the hijacked connection?

**Comment by zenazn** [comment]
Ooops--this is a bug. Fixed!
