### ISSUE TITLE
pprof with goji

### ISSUE THREAD

**Issue by sundarv85** [zenazn/goji#131]
Hello,

From [Profiling Go Programs](http://blog.golang.org/profiling-go-programs), I had added `import "net/http/pprof"`. And the following

	m.Get("/debug/pprof/", http.HandlerFunc(pprof.Index))
	m.Get("/debug/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
	m.Get("/debug/pprof/profile", http.HandlerFunc(pprof.Profile))
	m.Get("/debug/pprof/symbol", http.HandlerFunc(pprof.Symbol))

However, when I run `go tool pprof http://127.0.0.1:8000/debug/pprof/profile` I still don’t get any profile data. How to exactly use pprof with goji

**Comment by sundarv85** [comment]
Have tried adding [profile package](http://dave.cheney.net/2014/10/22/simple-profiling-package-moved-updated), this also does not capture the profile. I added it in the main function, where I call the graceful.ListenAndServe. What am I missing here...

**Comment by zenazn** [comment]
I just do the first bit (`m.Get("/debug/pprof/", ...)` etc.) in my Goji applications and it works for me. Is there something else that could be in play here?

(as an unrelated aside, the `http.HandlerFunc` is unnecessary)
