### ISSUE TITLE
Leaked request, or something gone wrong in app code

### ISSUE THREAD

**Issue by pkieltyka** [zenazn/goji#141]
I noticed the https://github.com/pressly/imgry server to be increasing goroutines over time (slowly), and after checking http://imgry3.x.pressly.io:4446/debug/pprof/goroutine?debug=2 I noticed that there are many requests that never end.. such as in: https://gist.github.com/pkieltyka/6d2f19abfd2f4489f163

.. what could be causing this..? a goroutine that blocks the request from returning? it would be nice to have net/context so I could force the goroutine chain after some timeout value

**Comment by zenazn** [comment]
That example in the gist is actually an HTTP client connection, so it's unrelated to Goji. 

We saw this in a high-traffic app I run, and we now set `TLSHandshakeTimeout` and `ResponseHeaderTimeout` on `http.Transport` to a few seconds a piece, and replace `Dial` with a custom `net.Dialer` that sets `Timeout` and `KeepAlive`. It's a lot of flags to frob, but I think that's fixed all the issues we've seen on the client side.

There are of course a few timeouts on `http.Server` (and therefore `graceful.Server`) that you can set if you're seeing issues on the server side.

**Comment by pkieltyka** [comment]
Thank you Carl!
