### ISSUE TITLE
New contrib Middleware: goji/csrf

### ISSUE THREAD

**Issue by elithrar** [zenazn/goji#144]
**goji/csrf** is Goji middleware that provides CSRF protection. You can find the 'review' repo here: https://github.com/elithrar/goji-csrf/tree/review

Design Notes:

* Designed to be very easy to use: the only required parameter is the authentication key (for signing cookies). All other options are optional and use sane defaults. Also takes a [functional options](http://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) approach instead of requiring a `nil` or `Options{}` when you just want to use the defaults. Just `goji.Use(csrf.Protect([]byte("hashkey")))` and you're most of the way there.
* Has a template helper that you can pass through `template.Execute` and it'll replace the `{{ .csrfField }}` tag in your templates with a `<input type="hidden" name="goji.csrf.Token" value="<token>">` field.
* Accepts a `web.Handler` to allow custom error pages on 403 errors, and provides a simple default that serves a 403, logs the error and writes out a plain text response.
* Falls back to a HTTP header if the form field is empty.
* Uses signed cookies via [gorilla/securecookie](https://github.com/gorilla/securecookie) and might provide a `Store` interface in the future for those who wish to use Redis/BoltDB/etc. Right now the means to use a custom store are private.
* Lots of tests that cover as much as reasonably possible. There's a couple of things relating to time fields that need some clock mocks, but aren't considered critical.
* The `var ErrSomeError` stuff (admittedly) isn't great, but it's familiar to most Go users and easy to reason with. I originally had an `Error` interface ([refer net.Error](http://golang.org/pkg/net/#Error)) with a concrete impl. and three methods, but tossed it after realising that it needed an example. Likely overkill in this case: outside of development, an error is a HTTP 403.

Usage example:

```go
package main

import (
    "github.com/goji/csrf"
    "github.com/zenazn/goji"
)

func main() {
    // Add the middleware to your router.
    goji.Use(csrf.Protect([]byte("32-byte-long-auth-key")))
    goji.Get("/signup", ShowSignupForm)
    // POST requests without a valid token will return a HTTP 403 Forbidden.
    goji.Post("/signup/post", SubmitSignupForm)

    goji.Serve()
}

func ShowSignupForm(c web.C, w http.ResponseWriter, r *http.Request) {
    // signup_form.tmpl just needs a {{ .csrfField }} template tag for
    // csrf.TemplateField to inject the CSRF token into. Easy!
    t.ExecuteTemplate(w, "signup_form.tmpl", map[string]interface{
        csrf.TemplateTag: csrf.TemplateField(c, r),
    })
    // We could also retrieve the token directly from csrf.Token(c, r) and 
    // set it in the request header - w.Header.Set("X-CSRF-Token", token)
    // This is useful if your sending JSON to clients or a front-end JavaScript
    // framework.
}

func SubmitSignupForm(c web.C, w http.ResponseWriter, r *http.Request) {
    // We can trust that requests making it this far have satisfied
    // our CSRF prevention requirements.
}
```

Looking to get this pulled into a `goji/csrf` repo under the existing Goji organisation once it's had a @zenazn review.

**Comment by zenazn** [comment]
This looks really nice! I've gone ahead and created `goji/csrf` and given you access—let me know if you need anything else from me, or if you want me to look over any other code

And as always, thanks a lot for your Goji contributions :)

**Comment by elithrar** [comment]
Thanks for the repo and the kind words!

I've pushed to master and have tagged it as a "v1.0rc1". I don't expect the API to change at all but it gives some room to move if any users have feedback early on or catch any bugs.

**Comment by elithrar** [comment]
Also: you might need to give me CI privs so I can add it to my Travis builds. The `goji/httpauth` repo appears to have the correct settings.

**Comment by zenazn** [comment]
I booped a button in the Travis webface (the same one I booped for `httpauth`). Maybe it'll start working now!

**Comment by elithrar** [comment]
Perfect: thanks!

**Comment by jeevatkm** [comment]
It's good to follow unique LICENSE for all modules under <code>github.com/goji/&lt;module_name></code> instead of different license for individual module(s).

Goji is [MIT](https://github.com/zenazn/goji/blob/master/LICENSE) and also all modules under <code>goji/*</code> is MIT except <code>goji/csrf</code> is [BSD](https://github.com/goji/csrf/blob/master/LICENSE)

**Comment by elithrar** [comment]
Note that the modules under the goji/* organisation are 'community'
modules, so it's probably more by coincidence that all but one is MIT
licensed. I licensed httpauth as MIT at the time, but I should have made it
BSD.

Since MIT & BSD are compatible, permissive licenses I don't think it's a
major problem: the only genuine difference is that the (3-Clause) BSD
license restricts a licensee from implicit promotion-by-association.

I'd *prefer* to keep goji/csrf BSD licensed but if Carl prefers to have
them all as MIT that's fine too.

**Comment by zenazn** [comment]
(I don't have a preference)

**Comment by jeevatkm** [comment]
:) Thanks.
