### ISSUE TITLE
Make goji.ServeListener() return error instead of using log.Fatal internally

### ISSUE THREAD

**Issue by nikolaybobrovskiy** [zenazn/goji#146]

**Comment by zenazn** [comment]
Are you running into this in production? What sort of behavior are you looking to perform with the resulting `error`?

I originally conceived of the top-level `goji` package as being a quick way to get started with `goji`, but which advanced users would inline and customize. In this vein, `Serve` and friends are designed to do opinionated reasonable things in the face of errors, etc.

This has clearly become less true with time, as a great many people (including me) have used the top-level `goji` package in production, so let me know what pain points you're running in to for which an `error` return would be helpful, and I'll see what I can do

**Comment by nikolaybobrovskiy** [comment]
The main point was to integrate it with own logger. Now I created own web.New() and use it instead of top level goji methods. I think it can be closed.
