### ISSUE TITLE
Extract logging and offer to clients

### ISSUE THREAD

**Issue by parkr** [zenazn/goji#147]
Hey! Thanks for this library, @zenazn. One question: it would be great to be able to log using goji's built-in logger so we can track output from each request. What do you think about this? Right now, any other logs don't get the benefit of the request ID and such. It'd be nice to use some global logger like `github.com/zenazn/goji/web.Logger` or something.

`web.Log(c, message)`
`web.Logf(c, format, args...)`

**Comment by zenazn** [comment]
Actually at work I wrote a package that exposes more or less this exact interface :). I'll look into open-sourcing it, but in the meantime feel free to drop me a personal email and I can share a preview of it with you

**Comment by pkieltyka** [comment]
what I've been doing in my projects is copying the simple logger middleware from goji and putting into my own project and swapping the actually logger with my own (in my case, Logrus)

**Comment by parkr** [comment]
Any movement here?

**Comment by parkr** [comment]
Any movement here?

**Comment by zenazn** [comment]
Sorry, haven't gotten the chance to do this yet :/

**Comment by canhlinh** [comment]
@parkr : You can use https://github.com/Innovatube/log4go . I have implemented to support goji middleware logging.
