### ISSUE TITLE
How to run http2

### ISSUE THREAD

**Issue by dre1080** [zenazn/goji#152]
How can I run Goji graceful server with bradfitz's [http2](https://github.com/bradfitz/http2) pkg.
`http2.ConfigureServer` takes in a `http.Server`

**Comment by elithrar** [comment]
Just quickly as I'm about to head out:


r := web.New()
r.Get("/", func(w http.ResponseWriter, r *http.Request) {
io.WriteString(w, "Goji!\n")
})

srv := &http.Server{
Addr:    ":8000",
Handler: r,
}

http2.ConfigureServer(srv, &http2.Server{})

This is half of an example based on the http2 example in the http2 repo:
https://github.com/bradfitz/http2/blob/master/h2demo/h2demo.go - but should
be enough to fill in the gaps. If you don't have any luck let me know where
you get stuck and post your code.

**Comment by dre1080** [comment]
Thanks, but how would I combine this with package `graceful`. eg. `graceful.ListenAndServeTLS` or `graceful.Server`?

**Comment by elithrar** [comment]
You should be able to configure a &graceful.Server{} instead and pass that:
https://godoc.org/github.com/zenazn/goji/graceful#Server

**Comment by dre1080** [comment]
No, that returns an error: `cannot use srv (type *graceful.Server) as type *http.Server in argument to http2.ConfigureServer`

**Comment by elithrar** [comment]
gf := graceful.Server{
Addr:    ":8000",
Handler: r,
}

srv := http.Server(gf)
http2.ConfigureServer(&srv, &http2.Server{})

That should work. As per the docs, graceful.Server is a http.Server with
different behaviour. I've tested this to work (at least, it runs!) with the
h2demo.go in the http2 package.

**Comment by dre1080** [comment]
Thanks. Is there a way to test that this http2 server is running gracefully?

**Comment by elithrar** [comment]
@dre1080 Sorry for the slow reply. I haven't had time to test—you could fire some requests at it and see if it bails out when you send it a SIGINT - e.g.

```go
gf := graceful.Server{
Addr:    ":8000",
Handler: r,
}
graceful.Timeout(time.Second * 20)

srv := http.Server(gf)
http2.ConfigureServer(&srv, &http2.Server{})
```

If the server doesn't wait 20 seconds then it's not handling it gracefully.

**Comment by zenazn** [comment]
This issue hasn't been updated in a while, and I'm going to assume that you've already managed to get Goji and HTTP 2 working together. If that's not the case, please feel free to reopen this issue (or make a new one entirely)!
