### ISSUE TITLE
Multiplexing on Host: headers ("virtualhosts")

### ISSUE THREAD

**Issue by elithrar** [zenazn/goji#158]
I figured I'd ask here to see if there's a cleaner way of multiplexing based on host headers to different muxes. 

Context (ignore the scratchy code—just a dev env):

```go
	ember := http.FileServer(http.Dir("/path/to/ember-go/dist/"))
	r := web.New()
	// r.Use(...)
	// The Ember entry point
	r.Get("/", ember)
	// Static assets
	r.Get("/assets/*",
		http.StripPrefix("/assets/",
			http.FileServer(http.Dir("/path/to/ember-go/dist/assets"))))
	// Force Goji to serve 404's to Ember so that directly browsing to a route allows Ember to handle it
	r.NotFound(func(w http.ResponseWriter, r *http.Request) {
		http.ServeFile(w, r,
			"/path/to/ember-go/dist/index.html")
	})
```

In addition:

* I have my API endpoints on a sub-router that's handling `/api/*` — this is the one I'd like to change to handle requests for `api.domain.com` rather than a `/api/` prefix.
* The `NotFound` function on the sub-router returns a 404 with a JSON body
* Can't use nginx to serve the static content directly as this will be hosted on Heroku, so Go needs to do the work.

I'd like to instead pass requests to muxes based on the `Host` header - e.g. `www.domain.com` and `api.domain.com` — similar to how gorilla/mux has a `.Host()` method as part of its router - e.g.

* The root handles all incoming requests for `/*` 
* Based on the `Host:` header it passes the request (with the request URI intact) to the relevant sub-router
* Calls its own 404 if no matches.

The obvious (to me) way would be to:

* Write some middleware of the form `func(c *web.C, h http.Handler) http.Handler` that sits on the "root" router
* Manually construct a `map[string]http.Handler` mapping hosts to routers
* Checks the `Host: ....` header (after cleaning it)
* Call the appropriate sub-router based on the map lookup e.g. `_, exists := hosts[cleanHost(r.Host)].ServeHTTPC(c, w, r)` else 404 if `!exists`.

But that seems pretty clunky. Is there a way that `mux.Router` could be used here? The important part is serving both on the same HTTP(S) port.

**Comment by zenazn** [comment]
One way to do this is to mix-and-match muxes. For instance, the stdlib mux does a pretty good job of dealing with `Host` headers; you could split things out there.

Depending on your use case, you can also write a custom `Pattern` type that additionally matches against the `Host` header.

This is of course also possible to do with middleware, although I don't think that abstraction maps particularly well to this scenario.

**Comment by elithrar** [comment]
Thanks for the reply @zenazn 

Forgot that `http.ServeMux` did that by default. I've been trying to lean on Goji's mux as the "root" mux so it can apply top-level middleware (the recoverer & CSRF) but repeating the middleware on each of the sub-routers might not be a huge problem.

Right now I have the below (using closures for quick testing):

```go
	hosts := map[string]http.Handler{
		"localhost:8000":     static,
		"api.localhost:8000": api,
	}

	mux := func(w http.ResponseWriter, r *http.Request) {
		if vh, exists := hosts[r.Host]; exists {
			vh.ServeHTTP(w, r)
			return
		}
		w.WriteHeader(404)
		return
	}

	r.Handle("/*", mux)
        // Sub-router routes below below...
```

I'm likely to adapt the above to match on `Host` explicitly first — `api.domain.com` — and if there's no matching host <=> router relationship, pass *all* requests to the fallback router (which would be the static router). Would save having to explicitly lay out all of the hosts you want to handle—pass the `api` ones to the API router, and pass the rest to the default.

Is there a concise or more flexible way to achieve this with `Pattern`?

**Comment by zenazn** [comment]
Sorry—didn't notice your final question here. There's not a great way to do this with `zenazn/goji`'s `Pattern`, but as I'm sure you've figured out by now `goji.io`'s `Pattern` is much more flexible here and is a far better fit for this use case.
