### ISSUE TITLE
Router doesn't distinguish between GET and HEAD

### ISSUE THREAD

**Issue by zhaytee** [zenazn/goji#159]
When two routes have the same structure but handle different HTTP verbs, Goji fails to match requests to the correct handler. This is demonstrated by the following Go code.
```go
package main

import (
	"log"
	"net/http"

	"github.com/zenazn/goji"
	"github.com/zenazn/goji/web"
	"github.com/zenazn/goji/web/middleware"
)

func main() {
	sub := web.New()
	sub.Use(middleware.SubRouter)
	sub.Get("/resource/:id", func(c web.C, w http.ResponseWriter, r *http.Request) {
		log.Println("hit the GET handler")
		w.Write([]byte("hello"))
	})
	sub.Head("/resource/:id", func(c web.C, w http.ResponseWriter, r *http.Request) {
		log.Println("hit the HEAD handler")
		w.WriteHeader(http.StatusNoContent)
	})

	goji.Handle("/sub/*", sub)
	goji.Serve()
}
```

One would expect `curl -v http://localhost:8000/sub/resource/1234` to return a `200 OK` response with a body of `hello`, while `curl -v -X HEAD http://localhost:8000/sub/resource/1234` should return a `204 No Content` response with no body. Here are the actual results from my testing:

```
$ curl -v http://localhost:8000/sub/resource/1234
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /sub/resource/1234 HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 18 Sep 2015 19:09:44 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
<
hello

$ curl -v -X HEAD http://localhost:8000/sub/resource/1234
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> HEAD /sub/resource/1234 HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 18 Sep 2015 19:10:41 GMT
< Content-Length: 5
< Content-Type: text/plain; charset=utf-8
<
```

So obviously something's up, and Goji's output reveals what that is:

```
2015/09/18 12:09:44.187942 [localhost/xvpb8foGKg-000003] Started GET "/sub/resource/1234" from 127.0.0.1:53188
2015/09/18 12:09:44.187967 hit the GET handler
2015/09/18 12:09:44.187981 [localhost/xvpb8foGKg-000003] Returning 200 in 19.502µs
2015/09/18 12:10:41.384716 [localhost/xvpb8foGKg-000004] Started HEAD "/sub/resource/1234" from 127.0.0.1:53221
2015/09/18 12:10:41.384741 hit the GET handler
2015/09/18 12:10:41.384755 [localhost/xvpb8foGKg-000004] Returning 200 in 18.414µs
```

Both requests are hitting the GET handler function!

Even stranger still is that if the routing calls are reversed (i.e. `sub.Head()` is moved above `sub.Get()`) then the code sample above works as expected.

**Comment by zenazn** [comment]
This is expected and documented behavior: http://godoc.org/github.com/zenazn/goji/web#Mux.Get

**Comment by zhaytee** [comment]
Ah! Sorry about that.
Might this have some unintended consequences, though? I've noticed that the GET handler from the above code sample, when executed by Goji to handle a HEAD request, causes curl to hang after the headers are received. The explicit HEAD handler works normally (i.e. the connection is closed after the headers are sent). Just something I noticed.

**Comment by zenazn** [comment]
Hm—that's weird! All the HEAD behavior is handled natively by `net/http`, so I'm not sure I understand what's happening there. Can you reproduce it using `net/http`?

**Comment by zenazn** [comment]
This issue hasn't been updated in a while, so I'm going to assume you figured this out. Please feel free to reopen this issue if you're still having problems with `HEAD` and `GET`!
