### ISSUE TITLE
Unexpected middleware call on non-matching route

### ISSUE THREAD

**Issue by VojtechVitek** [zenazn/goji#160]
Given

```go
package main

import (
	"net/http"

	"github.com/zenazn/goji"
)

func Middleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("POST only middleware!\n"))
		next.ServeHTTP(w, r)
	})
}

func Post(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("POST only!\n"))
}

func main() {
	goji.Use(Middleware)
	goji.Post("/", Post)
	goji.Serve()
}
```

The above `Middleware` is executed on every request, even on non-matching routes, which doesn't sound right to me.

```bash
$ curl -X GET localhost:8000
POST only middleware!
404 page not found
```

Is this expected/documented behavior of Goji?

**Comment by elithrar** [comment]
Middleware is attached to a router—effectively the same as `http.ListenAndServe(PORT, middleware(router))`. All requests/responses pass through it—which makes sense because the router is still handling non-matching requests by responding with a 404.

**Comment by zenazn** [comment]
Yup—all middleware is applied before any routing is performed. This is a source of confusion for a lot of people and can probably be documented a lot better.

**Comment by zenazn** [comment]
This issue hasn't been updated in a while, so I'm going to assume you figured out Goji's middleware semantics. Please reopen this issue (or open a new one) if you're still confused!
