### ISSUE TITLE
Issue with Mux's handle method

### ISSUE THREAD

**Issue by dhawal55** [zenazn/goji#161]
I'm trying to use nested muxes and goji's mux's handle method does not behave as expected.
Here's the code. If you replace ```parentMux := web.New()``` with ```parentMux := http.NewServeMux()```, it works 
```
package main

import (
	"io"
	"net/http"

	"github.com/zenazn/goji/web"
)

func main() {
	child1Mux := http.NewServeMux()
	child1Mux.HandleFunc("/foo", func(w http.ResponseWriter, r *http.Request) {
		io.WriteString(w, r.URL.Path)
	})

	child2Mux := http.NewServeMux()
	child2Mux.HandleFunc("/bar", func(w http.ResponseWriter, r *http.Request) {
		io.WriteString(w, r.URL.Path)
	})

	parentMux := web.New()
	parentMux.Handle("/", child1Mux)
	child1Mux.Handle("/", child2Mux)

	http.ListenAndServe(":8181", parentMux)
}
```

**Comment by zenazn** [comment]
Goji patterns have different semantics than `http.ServeMux`: all patterns much match exactly, even if they contain a trailing slash. You're probably looking for `"/*"`, which matches a prefix of the URL.

**Comment by dhawal55** [comment]
Thank you.
