### ISSUE TITLE
What is the best way to handle dynamic subdomains? 

### ISSUE THREAD

**Issue by dre1080** [zenazn/goji#162]
An example is if you wanted users to have their own subdomains like GitHub Pages: `{username}.github.io`

**Comment by zenazn** [comment]
Goji doesn't provide anything natively, but you can probably scrape this out of the request's https://godoc.org/net/url#URL

**Comment by zenazn** [comment]
Closing this to keep things clean, but let me know if you're still having troubles with subdomains.
