### ISSUE TITLE
Serve routes from root as well as static files

### ISSUE THREAD

**Issue by jchannon** [zenazn/goji#164]
Hi

Is there a way to serve routes from root as well as static files?

<img width="759" alt="screen shot 2015-11-07 at 19 15 22" src="https://cloud.githubusercontent.com/assets/105126/11016831/3eb0e030-8584-11e5-8197-e485b816ec1a.png">

I think I understand why the above example fails ie/the first route is capturing everything, but is there a way to make this example work?

**Comment by jchannon** [comment]
I guess the solution is to reorder the routes so the greedy one is last

<img width="426" alt="screen shot 2015-11-07 at 19 22 14" src="https://cloud.githubusercontent.com/assets/105126/11016854/ef6f8f16-8584-11e5-9e98-7ad844e8ba8b.png">

**Comment by elithrar** [comment]
Correct - the catch-all route should be last.

**Comment by zenazn** [comment]
The broad principle here is that routes are attempted in the order they are added. Putting the catch-all route first means that routes below it never get a chance to run.
