### ISSUE TITLE
Content Negotiation

### ISSUE THREAD

**Issue by jchannon** [zenazn/goji#165]
Is there content negotiation capability in goji?

**Comment by jchannon** [comment]
Could maybe adapt this to work with goji https://libraries.io/go/github.com%2Fdivideandconquer%2Fnegotiator

**Comment by elithrar** [comment]
Can you explain the use case? net/http (and therefore Goji) will already
set Content-Type headers by sniffing the content - e.g. if you write JSON
to the response, Go will set the header to `application/json`.

**Comment by jchannon** [comment]
I'm not sure how it would work in go but conneg basically writes the object
to the response/stream based on the Accept header.

So if you have /users/1 with Accept as application/json you get back json.
If the Accept header is application/xml you get back xml.

Rather than having an if block in every handler there is something
somewhere that says oh the client wants representation X so let's take your
user object and serialise it accordingly

**Comment by elithrar** [comment]
Having a look at it now on my desktop: it should work out of the box with Goji. It's just that you can't share a global instance because it wants to be initialised to a `http.ResponseWriter` (but doesn't actually use it to write anything for you with).

This should work (untested, but still):

```go
func main() {

    r := web.New()
    r.Get("/some-content", SomeHandler)
    // ...
}

func SomeHandler(c web.C, w http.ResponseWriter, r *http.Request) {
    users, err := db.GetUserList(25)
    if err != nil {
        http.Error(w, http.StatusText(500), 500)
        return
    }

    cn := negotiator.NewJsonXmlContentNegotiator(negotiator.JsonEncoder, w, true)
    b, err := cn.Negotiate(r, users)
    if err != nil {
        http.Error(w, http.StatusText(500), 500)
        return
    }

    w.Write(b)
}
```

Otherwise you can just write a helper function - e.g. `AutoResponseEncoder(default Encoder, w http.ResponseWriter, data interface{}) error` and have it use a switch-case internally to write out either JSON, XML, <whatever> or fallback to your specified default.

If you're not sure on how to approach the above let me know and I'll pull together a reasonably polished demo a bit later today.

**Comment by zenazn** [comment]
This sounds to me like a layer of abstraction that should be completely separate from routing. I've never used `github.com/divideandconquer/negotiator` but it (or any other library that uses standard `net/http` types) should work just fine with Goji.

Depending on your application, and depending on how difficult or frustrating negotiating content types in each handler is, it might make sense to invent another handler type, e.g., `type MyHandler func(http.ResponseWriter, *http.Request) (interface{}, error)` (or similar), and a wrapper function with signature `func(MyHandler) goji.Handler` that is responsible for looking at the returned `interface{}` and the requested content-type and serializing it appropriately. I think there's a post on the Golang blog that explains how to do something like this.

**Comment by jchannon** [comment]
Its definitely something separate from the routing.

I think there are 3 approaches: 
i) I think you either need to inspect the body at a middleware level and somehow convert what's in it to json/xml/html/pdf 
ii) You need an object where you store a model on it and then serialise accordingly then write to the responsewriter.
iii) have a switch statement in every handler to say if Accept header == X seriliese to json/xml/html

I'd be interested to see @zenazn wrapper handler approach

**Comment by jchannon** [comment]
I've had a bash at number (ii) using the context where I have a handler that puts a object into `c.Env`

```
func getTweetById(ctx web.C, w http.ResponseWriter, req *http.Request) {
	id, err := strconv.Atoi(ctx.URLParams["id"])
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	tweet := tweets[id]
	ctx.Env["model"] = tweet
}
```

I then have some middleware that inspects the `c.Env` and acts accordinly however I can't seem to get the ordering of the middleware working. No matter where I put the middleware it always seems to go through my middleware and then hit my handler.
```
func Conneg(c *web.C, h http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {

		accept := r.Header.Get("Accept")
		model := c.Env["model"]
		
                switch accept {
		case "application/json":

			w.Header().Set("Content-Type", "application/json")

			js, err := json.Marshal(model)

			if err != nil {
                                http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}

			w.Write(js)
		case "application/xml":
			w.Header().Set("Content-Type", "application/xml")
			w.Write([]byte("<xml><name>xml</name></xml>"))
		}

		h.ServeHTTP(w, r)
	}
	return http.HandlerFunc(fn)
}
```  

I've opened #166 due to this minor issue

**Comment by zenazn** [comment]
The `h.ServeHTTP(w, r)` line in your middleware is where your handler runs. You'll want to place your content negotiation code after that point for it to be effective.

**Comment by jchannon** [comment]
Thanks got it working. Would you like a conneg middleware PR submitted to add to the collection?

**Comment by zenazn** [comment]
I don't know how easy it will be to write something generic and useful enough for general consumption, but if you end up writing something I'd encourage you to add it to the Goji third-party library list: https://github.com/zenazn/goji/wiki/Third-Party-Libraries

**Comment by jchannon** [comment]
Here's my lib, will add it to the list

https://github.com/jchannon/negotiator
