### ISSUE TITLE
Access to next middleware

### ISSUE THREAD

**Issue by jchannon** [zenazn/goji#166]
Hi!

I've been trying to write some middleware under the presumption that it works like so:

```
Middleware1
  Middleware2
Middleware1
Final Response
```

I believe the goji middleware doesn't work like that? If wrong how do I make it work like that?

Thanks :smile:

**Comment by jchannon** [comment]
Ah, I see you have to serve the requests and then you can do some things afterwards like the logger does https://github.com/zenazn/goji/blob/46b46e00f46dda650e04f0bceeb7c40732cd5988/web/middleware/logger.go#L35

**Comment by zenazn** [comment]
Sorry, I'm not sure I understand what you're asking.

In case it's helpful, Goji middleware are just composable functions: setting aside contexts for the time being, `mux.Use(a); mux.Use(b)` is equivalent to wrapping handlers like so `wrappedHandler := a(b(myHandler))`. It's each middleware layer's responsibility to call its "inner" layer if it chooses—that is, the `http.Handler` it is passed as an argument.

**Comment by jchannon** [comment]
Apologies for all the code but this is what I have:

```
tweets := web.New()
goji.Handle("/tweets/*", tweets)
tweets.Use(middleware.SubRouter)
tweets.Get("/:id", getTweetById)
tweets.Use(Conneg)

func getTweetById(ctx web.C, w http.ResponseWriter, req *http.Request) {
	id, err := strconv.Atoi(ctx.URLParams["id"])
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	tweet := tweets[id]

	ctx.Env["model"] = tweet
}

func Conneg(c *web.C, h http.Handler) http.Handler {
	fn := func(w http.ResponseWriter, r *http.Request) {

		h.ServeHTTP(w, r)

		accept := r.Header.Get("Accept")
		model := c.Env["model"]
		fmt.Println(c.Env["model"])
		switch accept {
		case "application/json":

			w.Header().Set("Content-Type", "application/json")

			js, err := json.Marshal(model)

			if err != nil {
				w.Write([]byte("oops" + err.Error()))
				//http.Error(w, err.Error(), http.StatusInternalServerError)
				return
			}

			w.Write(js)
		case "application/xml":
			w.Header().Set("Content-Type", "application/xml")
			w.Write([]byte("<xml><name>xml</name></xml>"))
		}
	}
	return http.HandlerFunc(fn)
}

```

So when i hit /tweets/1 it stores the tweet in the `Env` then the `Conneg` middleware uses it to issue the serialised data.  

However I don't understand how this works, I would understand if I set the routing up like:

```
tweets.Use(Conneg)
tweets.Get("/:id", getTweetById)
```

**Comment by zenazn** [comment]
Ah—`Use` and the various `Handle` (and HTTP methods) functions are independent registration processes, and the order in which you interleave them is irrelevant. You can put all of your `Use`'s first and your route registrations second, or all your routes first and your middleware second, or you could alternate between middleware and routes (I don't recommend this one), and the result would all be the same. Only the relative orderings between items of a given category matter.

Hopefully that clears things up!

**Comment by jchannon** [comment]
Aha! Thanks :)

I assume it matters the order of the Use statements if you have multiple
middleware however?

**Comment by jchannon** [comment]
In fact I've just proved it does locally :smile: 

Thanks again
