### ISSUE TITLE
Recommendations on binding json to struct

### ISSUE THREAD

**Issue by jchannon** [zenazn/goji#167]
Hi

I've looked at the example and it uses `parse` but I can't see the code for that on Github.  Can you recommend a model binder that can bind form body and json body data?

Thanks

**Comment by elithrar** [comment]
https://github.com/goji/param and https://github.com/gorilla/schema

**Comment by renstrom** [comment]
I might misunderstand but for JSON you can do something like this:

```go
type Person struct {
    Name string `json:"name"`
    Age int `json:"int"`
}

func myHandler(w http.ResponseWriter, r *http.Request) {
    p := &Person{}
    defer r.Body.Close()
    json.NewDecoder(r.Body).Decode(p)
    // ...
}
```

**Comment by jchannon** [comment]
@renstrom thats what I've gone with for now, but now I need validation. I found this https://github.com/mholt/binding but I don't really like the fieldmapper approach, i'm quite happy with reflection in model binding but i can't see a better validation library. adding struct tags everywhere can get ugly and too verbose and complicated over time IMO
