### ISSUE TITLE
Restart webserver on file change

### ISSUE THREAD

**Issue by jchannon** [zenazn/goji#168]
I've looked at `fresh` and also `nodemon` but for some reason when a file changes the server isnt restarted.  I'm assuming this is because goji supports a graceful shutdown so is not shutting down and restarting properly?

I tried something like the below but that doesn't work either:
```
	goji.Get("/*", http.FileServer(http.Dir("static")))
	//goji.Serve()
	http.ListenAndServe(":8000", goji.DefaultMux)
```

Any ideas?

**Comment by zenazn** [comment]
I don't think graceful shutdown should a factor here, especially if you're running without the `graceful` package at all (i.e., like your example snippet).

I don't know very much about how these auto-reloading tools work, so it might make sense to file an issue against one of those other projects instead (but let me know if I can help with any of the Goji parts!)

**Comment by elithrar** [comment]
Can you share how you're using `fresh` to check for changes?

I'm a user of reflex (https://github.com/cespare/reflex) - running `reflex
-r '\.*go' go build` in a tmux pane, if that helps solve your problem in
another way :)

**Comment by jchannon** [comment]
Tried reflex and it threw errors 
![screen shot 2015-11-10 at 09 30 20](https://cloud.githubusercontent.com/assets/105126/11058873/b7ac46f4-878d-11e5-9c12-607b43f50443.png)

**Comment by renstrom** [comment]
From the looks of it, it seems it's not correctly excluding files from your `node_modules` directory.

**Comment by jchannon** [comment]
Yeah, a colleague tried it and for him it just hanged and didnt do anything

**Comment by elithrar** [comment]
Why not run it from within the folder where your Go project is? Do you need it to watch all of your node dependencies?

**Comment by jchannon** [comment]
I am, i'm in the root of my project and i only want to watch go files

**Comment by renstrom** [comment]
Your image says otherwise "Error while watching new path **node_modules**/...: too many open files". So your exclude pattern isn't working.

**Comment by renstrom** [comment]
Besides, sounds like an issue for Reflex, not Goji?

**Comment by Yantrio** [comment]
<img width="421" alt="screen shot 2015-11-10 at 09 45 19" src="https://cloud.githubusercontent.com/assets/237469/11059145/d09df386-878f-11e5-930f-4386fe3d0389.png">

It seems to be something to do with how reflex is or isnt passing the kill signal to go / goji. I can't seem to get it  to reboot

**Comment by jchannon** [comment]
Which leads me back to my initial thought that I wonder if the graceful shutdown is too graceful for these tools :smile:

**Comment by jchannon** [comment]
Eureka! This works ` reflex -s -r '\.*go' -R node_modules/ go run main.go`

Thanks @elithrar for the recommendation
