### ISSUE TITLE
Adding routing constraints

### ISSUE THREAD

**Issue by jchannon** [zenazn/goji#172]
Hi,

I was wondering on your thoughts on adding routing constraints that allow returning "types" from `c.URLParams["id"]`

For example when you have something like `goji.Get("/product/:id{int}", hello)`, when you pull do `id := c.URLParams["id"]` the type will be integer, that way it allows you to prevent `atoi` conversions if you have a few routing arguments

**Comment by zenazn** [comment]
It's certainly a good idea, but writing the type signatures here gets messy very quickly, and you end up with `interface{}` leaking everywhere. I'd encourage you to give this a shot, but based on what I know I don't think it's going to work well for Goji.

Incidentally, the new version of Goji (https://github.com/goji/goji) can theoretically support cases like this, although I've yet to write an implementation.
