### ISSUE TITLE
Add support for fasthttp

### ISSUE THREAD

**Issue by valyala** [zenazn/goji#173]
It would be great if goji adds support for [fasthttp](https://github.com/valyala/fasthttp) - http library optimized for speed.

**Comment by zenazn** [comment]
I'm not interested in adding `fasthttp` support—IMO the benefits Goji (and the rest of the Go ecosystem) are getting out of `net/http` standardization far outweigh the benefits most people will see from (admittedly impressive) performance improvements. 

Sorry about that!

**Comment by valyala** [comment]
No problems - I see that goji values simplicity, while fasthttp values performance. So there is little sense trying to use them together :)
