### ISSUE TITLE
Suggest middleware for request URL.Query()

### ISSUE THREAD

**Issue by tesujimath** [zenazn/goji#174]
I have several middlewares that need query parameters.  However, each call to r.URL.Query() parses the query string, and this is not a no-op.

Therefore I have made a middleware which does this once, and stores it in c.Env.

Would you accept a pull request for this?

**Comment by zenazn** [comment]
Sure!

(I've actually been trying to err on the side of pushing things out of the main Goji repo, but this seems general-purpose enough and small enough to be worth including).
