### ISSUE TITLE
Use different middleware for different routes with App Engine

### ISSUE THREAD

**Issue by johngb** [zenazn/goji#175]
It's already fairly clear how to set up different middleware for different routes when using standard Go, however, when it comes to using App Engine, it's not clear to me.  In App Engine, we have to pass in a `*web.Mux` to a `http.Handle` in the `init()`.

It would be possible to do it with something like this:

```Go
func init() {

m1 := web.New()
m1.Use(middleware1)
m1.Post("some/route", handler1)
http.Handle("/some/route", m1)

m2 := web.New()
m2.Use(middleware2)
m2.Post("some/other/route", handler2)
http.Handle("/some/other/route", m2)

...
}
```

While that would work well if the middleware acts on families of routes (such as "admin", or "user"), in cases where the middleware needed isn't as related, it would result in having calls like this for almost every handler, which would get messy.

Is there a clean way in App Engine of setting up a single `*web.Mux` to have different middleware groups that can be applied on a per route basis?  Alternatively is there any way of inlining middleware in the `m.Post()`, `m.Get()`, etc?

**Comment by elithrar** [comment]
The short answer is that you can wrap individual routes by providing a
handler that returns a compatible type - a web.HandlerFunc or web.Handler -
e.g. mux.Get("/", SomeMiddleware(SomeHandler)) where SomeMiddleware might
look like func(c web.C, w http.ResponseWriter, r *http.Request) { ... }

Middleware in general isn't wholly designed to apply to single routes
(middleware generally is a way to action the same logic over many routes),
which is why it's a little less obvious.

**Comment by zenazn** [comment]
This is unfortunately pretty hard to do within the confines of Goji's abstractions—like Matt said, Goji's middleware are designed to apply across all of your routes, and don't work well for a more pick-and-choose style.

You might find it a bit easier to use a standalone middleware / `http.Handler`-wrapping abstraction. Thankfully, the interfaces here are pretty straightforward to use, but unfortunately I'm not sure of a good off-the-shelf library that you can drop in. 

A brief note on AppEngine in particular: if you're looking to avoid the built-in `net/http` mux as much as you can, I'd suggest registering a Goji mux like so:

``` go
root := web.New()
http.Handle("/", root)
```

This allows you to "get out" of `net/http` as soon as possible, and let Goji handle all of your application's routing.
