### ISSUE TITLE
Post method with multipart/form-data encoding not work

### ISSUE THREAD

**Issue by maxim0r** [zenazn/goji#179]
I need to upload a file to the server. But does not work transfer form parameters with multipart/form-data encoding. Therefore it is not working csrf protection.
I wrote an example:
```
package main

import (
	"net/http"
	"github.com/zenazn/goji"
	"github.com/golang/glog"
)

func HelloServer(w http.ResponseWriter, req *http.Request) {
	w.Write([]byte(	`
	<html>
	<head>
	<title>Upload file</title>
	</head>
	<body>
	<form enctype="multipart/form-data" action="/" method="post">
	<input type="file" name="uploadfile" />
	<input type="hidden" name="testhidden" value="test123"/>
	<input type="submit" value="upload" />
	</form>
	</body>
	</html>
	`))
}

func HelloServerPost(w http.ResponseWriter, req *http.Request) {
	glog.Infof("testhidden:%v",req.PostFormValue("testhidden"))
	http.Redirect(w, req, "/", http.StatusCreated)
}

func main() {
	goji.Post("/", HelloServerPost)
	goji.Handle("/", HelloServer)
	goji.Serve()
}

```
testhidden parameter is empty.
This is a bug?

**Comment by zenazn** [comment]
This is going to be an issue with your use of `net/http`, not a bug with Goji. My suspicion is that you'll want to call `net/http.Request.ParseMultipartForm`, and then look at `net/http.Request.MultipartForm` directly.

**Comment by scrivy** [comment]
working example I recently wrote:

`func PostImages(c web.C, w http.ResponseWriter, r *http.Request) {
	err := r.ParseMultipartForm(10000000)
        // if err !=nil do something

	file, fileheaders, err := r.FormFile("file")
	if err != nil {
		http.Error(w, "failed to parse file", http.StatusBadRequest)
		return
	}
	defer file.Close()

        contents, err := ioutil.ReadAll(file)`

**Comment by maxim0r** [comment]
I'm sorry, I understood. Thank you.
