### ISSUE TITLE
returned 404 error when load js file

### ISSUE THREAD

**Issue by Fantasim** [zenazn/goji#180]
I do not quite understand the operation of goji with the assets.

i have created a topic on stackoverflow but no one have gave an answer i can apply.

http://stackoverflow.com/questions/35637196/returned-404-error-when-load-js-file/35637522?noredirect=1#comment58956657_35637522

If you can answered on topic or here, i would be very grateful .

thanks

**Comment by elithrar** [comment]
See my answer: http://stackoverflow.com/questions/35637196/returned-404-error-when-load-js-file/35638539#35638539
