### ISSUE TITLE
Document zenazn/goji vs goji/goji

### ISSUE THREAD

**Issue by mayhewj** [zenazn/goji#181]
It looks like [`goji/goji`](https://github.com/goji/goji) is the successor to this project. I think some documentation clarifying the differences between the projects and which one people should use would be helpful.

The [website](https://goji.io/) in this projects description also has an example for the newer version but tells users to `go get github.com/zenazn/goji`.

**Comment by zenazn** [comment]
Oops—the website should read `go get goji.io`. I've gone and fixed that

As for the broader question of `goji/goji` vs `zenazn/goji`, documenting it is still on my list, but I strongly encourage new projects to use `goji/goji`.
