### ISSUE TITLE
wrapping HandlerType

### ISSUE THREAD

**Issue by tcurdt** [zenazn/goji#182]
Obviously this cannot work

    func wrap(fn web.HandlerType) web.HandlerType {
     return func(c web.C, w http.ResponseWriter, r *http.Request) {
       log.Println("Before")
       fn(w, r)
       log.Println("After")
     }
    }

but I am wondering what could be the best non-middleware way of wrapping a handler?

**Comment by elithrar** [comment]
Do you just want to write something like `goji.Get("/route", Wrapper(Handler))` - ?

**Comment by tcurdt** [comment]
Yup - that's what I am after.

**Comment by elithrar** [comment]
```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/zenazn/goji"
	"github.com/zenazn/goji/web"
)

func main() {
	goji.Get("/", handler)
	goji.Get("/wrapped", wrap(handler))

	goji.Serve()
}

func handler(c web.C, w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "hello")
}

func wrap(h web.HandlerFunc) web.HandlerFunc {
	fn := func(c web.C, w http.ResponseWriter, r *http.Request) {
		log.Println("before")
		h.ServeHTTPC(c, w, r)
		log.Println("after")
	}

	return web.HandlerFunc(fn)
}
```

You need to use `web.HandlerFunc` as `web.HandlerType` is an alias for the empty `interface{}` (and hence has no methods you can call without type asserting). If you need to handle multiple handler types, copy the [type switch from here](https://github.com/zenazn/goji/blob/46b46e00f46dda650e04f0bceeb7c40732cd5988/web/handler.go#L29-L40).

PS: There's also a Goji v2 over at https://github.com/goji/goji

**Comment by tcurdt** [comment]
@elithrar thanks! That would be a useful addition to the docs.

Will use v2 for the new projects - this isn't :)
Is there a WHATSNEW for it?
