### ISSUE TITLE
goji routing with react-router

### ISSUE THREAD

**Issue by Fantasim** [zenazn/goji#185]
Hi,

I would like to know how goji work with with routing in front.
Because when i put : 

```
goji.get("/", Index)
goji.get("/topics/:id", Index)
goji.get("/images/:id, Index)
```

with my routing on react-router : 

```
	<Router history={browserHistory}>
		<Route path="/" component={Main}>
			<Route path="topic/:id" component={Topic} />
			<Route path="images/:id" component={ImageDetail} />
		</Route>
	</Router>
```

It works perfectly.

But when i put : 

`goji.get("/*", Index)`

and i load '/', i get this error in console : 

> Uncaught SyntaxError: Unexpected token < main.js 1

line 1 of main.js is :

` <html>`

have u an idea?

**Comment by elithrar** [comment]
`goji.get("/*", Index)` is not valid and would not compile. Is that what you have, or did you mean `goji.Get("/*, Index)`.

The error you're seeing is from React/your build process. Perhaps you also meant to have `        <Route path="/" component={Main} />` instead of  `component={Main}>` ?

**Comment by Fantasim** [comment]
Sorry i wanted to say goji.Get yes.

Error from react but i don't think thats from react only because if i put each route, its works

**Comment by zenazn** [comment]
Out of curiosity, is `main.js` an HTTP 404 page? Note that Goji doesn't serve files from the project's root by default—you'll have to use something like https://godoc.org/net/http#FileServer to configure Goji to serve your assets.

**Comment by Fantasim** [comment]
Hello,

No 404 http page

**Comment by snicol** [comment]
I'm using 

    <Route path="/" component={App}>

As well as 

    goji.Use(gojistatic.Static("web/public", gojistatic.StaticOptions{SkipLogging: false}))
    goji.Get("/*", GetIndex)

after all my routes (just before serve) and haven't run into an issue. Take a look at your route ordering and React compilation.
