### ISSUE TITLE
Headers matching 

### ISSUE THREAD

**Issue by d3sire** [zenazn/goji#186]
Is there any native way of matching headers like in `gorilla/mux`. Or using middleware for this is the only option in goji?

**Comment by elithrar** [comment]
Using middleware. There isn't a Headers() method like gorilla/mux.

**Comment by zenazn** [comment]
For what it's worth, Goji 2 (https://goji.io) gives you enough rope to write a `Pattern` type that matches on HTTP headers.

**Comment by d3sire** [comment]
@zenazn thanks. Where can I read about how Goji and Goji.io are integrated?

**Comment by zenazn** [comment]
The README in that project (https://github.com/goji/goji) and the GoDoc documentation (https://godoc.org/goji.io) should be helpful there!
