### ISSUE TITLE
Does Goji 2 have Einhorn support?

### ISSUE THREAD

**Issue by ragrum** [zenazn/goji#189]
Hi,

before anything else I want to thank you a lot for all the work on this project, I've using it along with Einhorn, and I'd like to know if the new version will have support for this, or do you think it isn't necessary anymore?

**Comment by zenazn** [comment]
I don't plan on including the `bind` and `graceful` packages in the https://github.com/goji/goji repository, but those packages in this repository are actually built entirely on `net/http`, and will work with any `net/http`-compatible mux, including Goji 2. If you're looking for Einhorn support in Goji 2, mixing and matching these packages is probably the way to go.
