### ISSUE TITLE
How to use goji.ServeTLS()

### ISSUE THREAD

**Issue by kitsushadow** [zenazn/goji#191]
I'm baffled at how to use the goji.ServeTLS

i see what it says about a config but i don't c what format the config needs to be in or what is expected vs optional etc

**Comment by zenazn** [comment]
Hey @kitsushadow— have you had a look at the documentation for `tls.Config` (https://godoc.org/crypto/tls#Config)? If the documentation isn't helpful, I'd search around the internet for guides—it's a standard type and should have plenty of tutorials
