### ISSUE TITLE
SubRouter unexpected 404

### ISSUE THREAD

**Issue by freezlite** [zenazn/goji#198]
Here is some code
```
package main

import (
	"fmt"
	"net/http"

	"github.com/zenazn/goji"
	"github.com/zenazn/goji/web"
	"github.com/zenazn/goji/web/middleware"
)

type handler struct{}

func (h handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	subMux := web.New()
	subMux.Use(middleware.SubRouter)
	subMux.Post("/:id", func(c web.C, w http.ResponseWriter, r *http.Request) {
		fmt.Fprint(w, "OK")
	})

	subMux.ServeHTTP(w, r)
}

func main() {
	goji.Handle("/inner/*", handler{})
	goji.Serve()
}
```
The main idea around this to encapsulate handler routes and use standart net/http Handler interface. So why the following code produce 404 and not use subrouter ?
```
curl -X POST http://localhost:8000/inner/5
404 page not found
```

**Comment by zenazn** [comment]
This is because Goji relies on the `web.C` argument of `ServeHTTPC` to keep its internal state. If you change your handler definition to read 
``` go
func (h handler) ServeHTTPC(c web.C, w http.ResponseWriter, r *http.Request) {
```
and the last line to read
``` go
	subMux.ServeHTTP(c, w, r)
```
everything should work! ✨

**Comment by zenazn** [comment]
(This version of Goji predates the standard library's `context` package, which solves some of these problems. Have a look at https://goji.io, a successor to this version of Goji, which doesn't have these problems!)

**Comment by freezlite** [comment]
I thought I can use SubRouter with the http.Handler interface. This will decrease code copling and will allow to use handler from another packages that didn't know anything about goji.

**Comment by zenazn** [comment]
`goji.io` can do that!
