### ISSUE TITLE
tag "v1.0" is a invalid module version

### ISSUE THREAD

**Issue by hollomyfoolish** [zenazn/goji#200]
It will show a error message "invalid module version v1.0" when use go mod build system, following the Semantic Versioning guid (https://semver.org/) v1.0.0 is a valid one.

**Comment by meeDamian** [comment]
Yes, please tag it as `v1.0.0`, otherwise `v0.9.0` is the latest version available (easily) when go mod is used…

**Comment by gbbr** [comment]
Tag `v1.0` still invalid version in 2020. Seems like nobody's home

**Comment by zenazn** [comment]
These tags predate the use of semver in the official Go tools, and I'm unwilling to delete git tags. So we're probably stuck with `v1.0` forever, unfortunately.

I've just tagged `v1.0.1`, though, so hopefully things will be better going forward!

**Comment by gbbr** [comment]
Thanks! That’s a perfect solution!

**Comment by meeDamian** [comment]
> I'm unwilling to delete git tags.

Perfect! :)

Simply creating another tag named `v1.0.0` would work, but `v1.0.1` is even better, thank you 🙌🏻.
