### ISSUE TITLE
func Serve() have no options to  disable log rquest 

### ISSUE THREAD

**Issue by tablecell** [zenazn/goji#201]
I run a benchmark compare framework preformance 
but can't find how to disable  goji  log 

  server.go  / func Serve()  have no options parameter 
```G

func init() {
	bind.WithFlag()
	if fl := log.Flags(); fl&log.Ltime != 0 {
		log.SetFlags(fl | log.Lmicroseconds)
	}

	graceful.DoubleKickWindow(2 * time.Second)
}

// Serve starts Goji using reasonable defaults.
func Serve() {
	if !flag.Parsed() {
		flag.Parse()
	}

	ServeListener(bind.Default())
}

```

**Comment by zenazn** [comment]
Have a look at the [`Mux.Abandon`](https://godoc.org/github.com/zenazn/goji/web#Mux.Abandon) function, which will allow you to remove the [`middleware.Logger`](https://godoc.org/github.com/zenazn/goji/web/middleware#Logger) middleware
