### ISSUE TITLE
zenazn/goji or goji/goji ?

### ISSUE THREAD

**Issue by tgbv** [zenazn/goji#204]
Hi! On this current project it's stated

> This project has been [superseded](https://github.com/goji/goji) by a new version of Goji by the same author

But `goji/goji` latest release is on 2018 while `zenazn/goji` latest release is on 2020

Which one of them should I pick?

**Comment by zenazn** [comment]
I'd still pick `goji/goji`! The inactivity is because we ran out of bugs to fix :)
