### ISSUE TITLE
c.URLParams available in middleware?

### ISSUE THREAD

**Issue by phea** [zenazn/goji#32]
I'm trying to access c.URLParams in a middleware function of mine, however c.URLParams doesn't seem to be initiated. I am either doing something wrong on my end or maybe URLParams is initiated after all the middleware calls. Anyone able to clarify.

**Comment by kurianCoding** [comment]
is it possible to set URL PARAMS in middleware?

**Comment by elithrar** [comment]
@kurianCoding You can just save over the map entry or create your own in middleware as you see fit - e.g. `c.URLParams["name"] = "Dave"` (before calling the next handler)

**Comment by kurianCoding** [comment]
@elithrar  thanks, I  had tried this method. It didn't work. I had a function that returns another function which is actually the middle ware. now its possible to send custom params using the c.Env. I was thinking about using a.URLParams because parameters show on the query string.
