### ISSUE TITLE
suggestion: tag releases

### ISSUE THREAD

**Issue by j1n6** [zenazn/goji#53]
I suggest that this project should tag releases on Github.

**Comment by hasryan** [comment]
Are there plans to make additional releases?  Last one was 0.9 in Jan 2015.  If not, should the master branch always be considered stable?

**Comment by zenazn** [comment]
@hasryan—The master branch is always stable. I've also just published a 1.0 release, in case that's more your cup of tea.

**Comment by hasryan** [comment]
@zenazn thank you!  I do like to use tagged releases when available.
