### ISSUE TITLE
Two useful patterns: Controllers and Responders - Thoughts?

### ISSUE THREAD

**Issue by pkieltyka** [zenazn/goji#79]
Hey @zenazn, just wondering your opinion on adding a controller-like handler in goji? I wrote my own that works with goji as a separate package, which I'd need to refine further to make it feel just right, but I find this is very useful once services start growing in size.

The fundamental difference between host most services are written in Go with http.Handler versus a controller is how a request passes through the mux. I believe both should be supported.

If using a controller to handle requests/responses, the controller still adheres to http.Handler, but it will actually instantiate a new controller object with the writer / request as instance variables of the controller and calls to the functions are the "actions" based on the routes specified on the controller itself. Think like in Ruby with rack + sinatra.

The benefits are its easy to have a context object that isn't a map of interface{}'s .. which is a huge pain in the ass when you're expecting to build real objects from the requests. Someone just walked into my office so I have to tend to that now, .. btw, this is similar to how gocraft and gin work.. beego tries to do this, but feels terribly awkward.

There are some pains to do this with Go in a clean way (without reflection), but its totally doable.

**Comment by zenazn** [comment]
I still look forward to seeing your ideas in action, but I'm going to close this issue since there's no longer anything to be done on the Goji side.
