### ISSUE TITLE
Named routes support

### ISSUE THREAD

**Issue by dre1080** [zenazn/goji#82]
Please add support for named routes. Something similar to gorilla mux http://www.gorillatoolkit.org/pkg/mux#Route.Name

**Comment by alehano** [comment]
I solve this problem like this https://github.com/alehano/reverse

**Comment by zenazn** [comment]
@alehano you should add that to the list of third-party libraries! https://github.com/zenazn/goji/wiki/Third-Party-Libraries

**Comment by alehano** [comment]
Ok, I did it.

**Comment by dre1080** [comment]
@alehano Thanks!

**Comment by faxal** [comment]
I'm looking at [gorilla/reverse](http://www.gorillatoolkit.org/pkg/reverse). It's just missing the prefix extraction that Goji has for a little bit more performance.
