### ISSUE TITLE
Feature request: make web.C to implement Context interface

### ISSUE THREAD

**Issue by c4milo** [zenazn/goji#85]
More info: https://blog.golang.org/context

**Comment by zenazn** [comment]
I've been reconsidering this, and think it might be worth it to make `web.C` implement `context.Context`. The implementation would look pretty much exactly as you imagined it: `web.C` would grow some extra methods, and would be appropriate for use in place of (e.g.,) `context.Background()`. Internally, Goji (and Goji middleware and handlers) would continue to use `web.C`.

I think doing this right would involve one pretty big breaking change: switching `web.C.Env` to a `map[interface{}]interface{}`. Most code could use the new map unchanged, but most `make` call sites would have to be updated. Additionally, I suspect many of the "standard" middleware would be changed to use `context`'s cute private-type hack instead of using string keys.

Anyways, I still have a bunch of reservations, and I'm not committing to changing anything, but I wanted to gauge the temperature of the room in advance of any changes. It's obviously a pretty big change (the change to `web.C.Env` in particular is probably the single biggest change I will ever make to the "core" Goji API) but I think there's a good chance it'll be worth it in the end.

**Comment by elithrar** [comment]
I'm curious to see what the benefits look like in real code.

What would the set/get operations look like when dealing with a web.C that
satisfies go.net/context — besides the additional private type (for the map
key)?

**Comment by zenazn** [comment]
Me too!

It would be ~exactly the same as it is currently, although you'd be encouraged (more than you currently are) to make your exposed type-safe helpers the primary means of getting and setting values.

**Comment by zenazn** [comment]
Alright, I've made the first change (making `web.C.Env` a `map[interface{}]interface{}`) on the "context" branch: https://github.com/zenazn/goji/tree/context (https://github.com/zenazn/goji/commit/d7a775b09b79d400ade6bb9d77e2e349d07bd41d)

I suspect this commit will end up in `master`: it's come up a fair bit, and I've long been convinced that if I were writing Goji from scratch I would have designed the interfaces this way.

I'm going to play around with this for a little while before making a call on `context.Context` compatibility. If nothing else, with the above change it'll be trivial to add in a third-party shim or at a later date, so I'll probably take my time to make sure I think it's a good idea.

In any event, please let me know about your Feels either here or by sending me a private email or something.

**Comment by sevein** [comment]
@zenazn, it's looking great so far! Nice works on the docs too.

**Comment by zenazn** [comment]
Ugh—thought of a case I hadn't previously considered: `web.C` isn't thread-safe. This was fine back when an entire middleware stack was processed in more-or-less a single-threaded manner, but `context.Context`'s seem like the sort of things that will wind up used across many goroutines.

This isn't a new problem (the possibility for ~this race has pretty much always been there), but I feel like it makes for a very exciting foot-gun.

**Comment by jlovison** [comment]
What about simply using a `context.Context` as the default context mechanism, and embedding `web.C` as a value to the initial context?

This way, web.C can be used as is (though still not thread-safe), but the remainder of the context interface remains standard in-line with net/context.

This would also allow rather easy migration:
* For existing middleware, just check in the `.Use` method whether the first paramater is a `web.C` or a `context.Context` -- if the former, just wrap it and pass the `context.Context`'s web.C.
* For existing code, authors just need to modify the funciton types and add a `c := ctx.Value("web.C")` (or whatever key is decided upon)

I question the utility of trying to replicate the existing `web.C` fuctionality as a `context.Context`, since, as you'd previously stated, middleware chains are remarkably synchronous, but bi-directional (hence, there are issues with an immutable context). However, there is absolutely an advantage to having a `context.Context` accessible as well (as an example case - a middleware that adapts context-based timeouts for different User-Agents of devices - mobile/desktop/etc).

It'd be nice to have the advantages of both, and since maps will always be mutable (passed by reference), you can just use `context.Context` and keep the advantages of `web.C` by making the latter a variable of the former, no?

**Comment by zenazn** [comment]
@jlovison—that's essentially the strategy I used with https://github.com/goji/context, and I have to say I'm not super thrilled about how awkward it feels.

I *am* considering making `func(c context.Context, w http.ResponseWriter, r *http.Request)` (and an equivalent `Handler`-esque type) allowed as handler types though—maybe that'll help?

**Comment by elithrar** [comment]
Adding another function signature to web.Handler would retain backwards
compat too, right?

Would mean that those who want to keep the existing web.C (and any
middleware they wrote) can continue to do so and/or weave in any
context.Context middleware as needed.

**Comment by zenazn** [comment]
Of course—I'd only add these if the community decided `func(c context.Context, w http.ResponseWriter, r *http.Request)` was the One True Context-ful Handler Type Of The Future (tm), and they'd be in addition to Goji's existing types.

**Comment by jlovison** [comment]
@zenazn - Yes!! I actually thought of this after thinking about the issue and re-reading your comments on #62, but had to run out before I could edit my comment.

I've racked my brain and come up with absolutely no instances where a context passed between middlewares on a per-request basis would need thread-safety given the sync sequencing of a middleware chain. And a huge part of the draw of goji for me is the simplicity and straightforwardness of the framework. If a `context.Context` is needed, there's nothing preventing adding it onto the `web.C.Env`, and implementing a `context.Context` across the entire request chain seems like a lot of potential complexity with very little return.

I completely concur - if suddenly we start seeing handlers cropping up following the pattern of `func(c context.Context, w http.ResponseWriter, r *http.Request)`, adding in code to handle this pattern would be nice, but until then, the work toward implementing `context.Context` would be solving a problem that has yet to exist.

I wonder though how amenable you'd be to changing from `web.C` to an interface based context at some point in the future (i.e. perhaps simply a URLParams Getter/Setter and an Env Getter/Setter), and allow for goji to set an override that conforms to that interface. ~~It'd be a breaking change whenever it was introduced, but~~ <sup>[1]</sup> it'd prevent any future changes to the context passing mechanism to break backwards-compatibility. It'd also alow framework users to plug-and-play contexts based on needs (i.e. if I somehow actually needed a mutable thread-safe implimentation, I could toss mutexes on the underlying implimentation and override goji's default. Or if I wanted to support `context.Context` I could add the goji interface's methods to a `context.Context` and override the default, etc).

<sup>[1]</sup> - Actually, I guess you could just add the getter/setter methods on the existing `web.C` struct, depreciating the map lookup pattern in the documentation. Legacy code would continue to work (and just be more tightly coupled to the underlying implimentation) but the framework itself would have loosened the coupling.

**Comment by zenazn** [comment]
Alright, `map[interface{}]interface{}` change has landed in master, and I've tagged a new release (`v0.9.0`)

**Comment by pkieltyka** [comment]
:+1: .. I'm beginning to think this is a good idea too

**Comment by gchaincl** [comment]
:+1: to `func(c context.Context, w http.ResponseWriter, r *http.Request)`, but
how are you planing to implement `ServeHTTPC(c C, w http.ResponseWriter, r *http.Request)`?

you should be able to get `contect.Context` from `web.C`.
Seems to me like `goji/context` should be integrated into `zenazn/goji` right?

**Comment by ceram1** [comment]
I tried somethings.. and made type-only library. 
[ceram1/chttp - handler.go](https://github.com/ceram1/chttp/blob/master/handler.go)
(originally not related to goji, but now I need goji)


and simple struct with embedded context will make tasks easier.

```go

import (
	"github.com/zenazn/goji/web"
	"golang.org/x/net/context"
)

type private int

var (
	paramsKey private = 1
	webCKey   private = 2
)

// URLParams is a map of variables extracted from the URL (typically
// from the path portion) during routing. See the documentation for the
// URL Pattern you are using (or the documentation for PatternType for
// the case of standard pattern types) for more information about how
// variables are extracted and named.
type URLParams map[string]string

func Params(c context.Context) URLParams {
	ps, _ := c.Value(&paramsKey).(URLParams)
	return ps
}

func WithParams(c context.Context, params URLParams) context.Context {
	return &paramCtx{
		Context: c,
		params:  params,
	}
}

type paramCtx struct {
	context.Context

	params URLParams
}

func (c *paramCtx) Value(key interface{}) interface{} {
	if &paramsKey == key {
		return c.params
	}

	return c.Context.Value(key)
}

// or

func WithWebC(c context.Context, wc web.C) context.Context {
	return &webCtx{
		Context: c,
		wc:      wc,
	}
}

type webCtx struct {
	context.Context

	wc web.C
}

func (c *webCtx) Value(key interface{}) interface{} {
	if &paramsKey == key {
		return c.wc.URLParams
	}
	if &webCKey == key {
		return c.wc
	}
	// TODO: check for env?

	return c.Context.Value(key)
}

```

**Comment by ceram1** [comment]
Is ```ContextFactory(r *http.Request)``` required?
Example usecase is appengine.NewContext(r)

**Comment by pkieltyka** [comment]
I really like the work in: https://github.com/vanackere/slim  .. I could see a lot of this working well.

**Comment by pkieltyka** [comment]
The middleware signature in slim (fork of goji), is pretty good, but it would be nice to see a standard structure for context.Context based http handlers right in the net/context package as a subpackage maybe like `net/context/chttp` that is super simple, just a handler and handlerfunc, essentially what http.Handler is, but for use with context.Context - then frameworks such as goji could use it and really get standardized around middlewares with a request context support built-in.

an example middleware with slim would look like..

```go
r := newRouter()
r.Use(CtxFun)
r.Use(CtxFun2)
r.Get("/", etc..)

func CtxFun(next web.Handler) web.Handler {
	return web.HandlerFunc(func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		log.Println("sup!")

		ctx = context.WithValue(ctx, "sup", 1)
		next.ServeHTTPC(ctx, w, r)
	})
}

func CtxFun2(next web.Handler) web.Handler {
	return web.HandlerFunc(func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		log.Println("fun2", ctx.Value("sup"))

		next.ServeHTTPC(ctx, w, r)
	})
}
```

it looks fine, and a step in the right direction (IMHO even for goji 2.0) - but I'd rather see the middleware as..

```go
import "golang.org/x/net/context/chttp"
func CtxFun3(next chttp.Handler) chttp.Handler {
	return web.HandlerFunc(func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		next.ServeHTTPC(ctx, w, r)
	})
}
```

**Comment by nbgo** [comment]
Generally it is not complex to make an adapter to Goji middleware.

1. Create context handler.
```
type ContextHandler interface {
	ServeHTTPContext(context.Context, http.ResponseWriter, *http.Request)
}

type ContextHandlerFunc func(context.Context, http.ResponseWriter, *http.Request)
func (this ContextHandlerFunc) ServeHTTPContext(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	this(ctx, w, r)
}

```

2. Create adapter for Goji.
```
package gnetty
import (
	"github.com/nbgo/netty"
	"net/http"
	"github.com/zenazn/goji/web"
	gcontext "github.com/goji/context"
	"golang.org/x/net/context"
)

type httpHandlerAdapter struct {
	h   netty.ContextHandler
	ctx *web.C
}
func (this httpHandlerAdapter) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	this.h.ServeHTTPContext(gcontext.FromC(*this.ctx), w, r)
}

type contextHandlerAdapter struct {
	h http.Handler
}
func (this contextHandlerAdapter) ServeHTTPContext(ctx context.Context, w http.ResponseWriter, r *http.Request) {
	c := gcontext.ToC(ctx)
	gcontext.Set(&c, ctx);
	this.h.ServeHTTP(w, r)
}

func ToGojiMiddleware(ctxMdlw func(netty.ContextHandler) netty.ContextHandler) func(*web.C, http.Handler) http.Handler {
	return func(ctx *web.C, h http.Handler) http.Handler {
		return httpHandlerAdapter{ctxMdlw(contextHandlerAdapter{h}), ctx}
	}
}

func ToGojiRoute(route func(c context.Context, w http.ResponseWriter, r *http.Request)) func(c web.C, w http.ResponseWriter, r *http.Request) {
	return func(c web.C, w http.ResponseWriter, r *http.Request) {
		route(gcontext.FromC(c), w, r)
	}
}
```

3. Create your own middlewares and routes.
```
func contextWriterMiddleware(h netty.ContextHandler) netty.ContextHandler {
	fn := func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		ctx = context.WithValue(ctx, "TestValue", "123")
		h.ServeHTTPContext(ctx, w, r)
	}

	return netty.ContextHandlerFunc(fn)
}

func contextReader(c context.Context, w http.ResponseWriter, r *http.Request) {
	ctxValue := c.Value("TestValue")
	w.Write([]byte(ctxValue.(string)))
}
```

4. Use with Goji like this.
```
mux := web.New()
mux.Use(gcontext.Middleware)
mux.Use(gnetty.ToGojiMiddleware(contextWriterMiddleware))
mux.Get("/", gnetty.ToGojiRoute(contextReader))
```

**Comment by pkieltyka** [comment]
@nbgo thanks for the example - I've done something similar but I'd prefer to see standardization around a context.Context based handler.

I noticed there is the `golang.org/x/net/context/ctxhttp` package which just helps with ctx based http clients, I feel this could also contain the context handler interfaces. I am going to submit a patch there.

**Comment by pkieltyka** [comment]
Here's the patch if anyone else is interested: https://go-review.googlesource.com/#/c/15620/   - it includes a test mux that works with http.Handler and ctxhttp.Handler.

**Comment by nbgo** [comment]
It is nice to have it in standard package.

**Comment by matrixik** [comment]
https://groups.google.com/d/topic/golang-dev/cQs1z9LrJDU/discussion

**Comment by elithrar** [comment]
Keep in mind that—if that proposal goes through—a Context field on
http.Request won't land until Go 1.7 in mid-2016 (> 8 months away).

@zenazn has been considering this but it may take some to materialize given
the potential changes to net/http.

In the meantime you can use https://github.com/goji/context to integrate
web.C with net/context

**Comment by pkieltyka** [comment]
btw, I've written a net/context router inspired by goji called `chi` -- https://github.com/pressly/chi  .. the core router is < 600 LOC and quite expressive. The hope is once net/context makes it into stdlib, and net/http uses context.Context natively, then I'll update chi accordingly.

**Comment by zenazn** [comment]
Closing, since Goji v2 (https://goji.io) implements this
