### ISSUE TITLE
"StrictSlash" Mode

### ISSUE THREAD

**Issue by elithrar** [zenazn/goji#9]
[gorilla/mux](https://github.com/gorilla/mux) provides a StrictSlash method that redirects routes missing a trailing slash to one with a slash (or vice versa), primarily for SEO and secondly for browser history clarity. 

It would be nice if Goji could provide a similar feature as part of its own router.

**Comment by jchannon** [comment]
I just found came across this and I dont think its too much magic. If I I have `Get("/env/")` and called it with both `/env` and `/env/` I'd expect both to be hit
